/*
 * Copyright (c) 2013-2025 NoSocial.Net & Ivan Khvostishkov. Co-authored with Amazon Q
 */

class FoodDatabase {
    static getFoodList() {
        return [
            // 01.1.1 Bread and Cereals (HICP monitored)
            'Wholemeal bread',
            'White bread',
            'Bread rolls',
            'Flour',
            'Pasta',
            'Rice',
            'Breakfast cereals',
            'Hot oat cereal',
            'Biscuits (sweet snacks / cookies)',
            'Crackers (savory with cheese)',
            'Couscous',
            'Quinoa',
            'Pearl barley',
            'Buckwheat',

            // 01.1.2 Meat (HICP monitored)
            'Beef',
            'Lamb',
            'Pork',
            'Chicken',
            'Fresh diced turkey',
            'Pork sausages',
            'Ham',
            'Bacon',
            'Liver',

            // 01.1.3 Fish (HICP monitored)
            'Fresh white fish fillets',
            'Canned tuna',
            'Fresh salmon fillets',
            'Frozen prawns',
            'Sardines',
            'Mackerel',
            'Cod',
            'Herring',

            // 01.1.4 Milk, Cheese and Eggs (HICP monitored)
            'Semi-skimmed milk',
            'Full-fat milk',
            'Butter',
            'Eggs',
            'Yoghurt',
            'Cheddar',
            'Parmesan',
            'Soft cheese',
            'Greek yogurt',
            'Cottage cheese',
            'Mozzarella',
            'Feta cheese',
            
            // Common Cheeses
            'Brie (cheese)',
            'Camembert (cheese)',
            'Gouda (cheese)',
            'Edam (cheese)',
            'Emmental (cheese)',
            'Gruyere (cheese)',
            'Stilton (cheese)',
            'Roquefort (cheese)',
            'Gorgonzola (cheese)',
            'Cheshire (cheese)',
            'Lancashire (cheese)',
            'Neufchatel (cheese)',
            'Munster (cheese)',
            'Comte (cheese)',
            'Beaufort (cheese)',
            'Reblochon (cheese)',
            'Saint-Nectaire (cheese)',
            'Cantal (cheese)',
            'Maroilles (cheese)',
            'Livarot (cheese)',
            'Pont-l\'Eveque (cheese)',
            'Epoisses (cheese)',
            'Langres (cheese)',
            'Chaource (cheese)',
            'Saint-Marcellin (cheese)',
            'Crottin de Chavignol (cheese)',
            'Sainte-Maure (cheese)',
            'Pouligny-Saint-Pierre (cheese)',
            'Banon (cheese)',
            'Cabecou (cheese)',
            'Picodon (cheese)',
            'Pecorino (cheese)',
            'Provolone (cheese)',
            'Caciocavallo (cheese)',
            'Ricotta (cheese)',
            'Fontina (cheese)',
            'Asiago (cheese)',
            'Manchego (cheese)',
            'Mimolette (cheese)',
            'Port-Salut (cheese)',
            'Saint-Paulin (cheese)',
            'Fourme (cheese)',
            'Blue Cheshire (cheese)',
            'Coulommiers (cheese)',
            'Vacherin (cheese)',
            'Tomme (cheese)',
            'Appenzell (cheese)',
            'Sbrinz (cheese)',
            'Tilsitt (cheese)',
            'Limburger (cheese)',
            'Herve (cheese)',
            'Laguiole (cheese)',
            'Rollot (cheese)',
            'Saint-Florentin (cheese)',
            'Soumaintrain (cheese)',
            'Vendome (cheese)',
            'Brillat-Savarin (cheese)',
            'Excelsior (cheese)',
            'Fontainebleau (cheese)',
            'Petit-Suisse (cheese)',
            'Broccio (cheese)',
            'Venaco (cheese)',
            'Chevrotin (cheese)',
            'Rigotte (cheese)',
            'Selles-sur-Cher (cheese)',
            'Pelardon (cheese)',
            'Chabichou (cheese)',
            "Carre de l'Est (cheese)",
            'Gerome (cheese)',
            'Gris de Lille (cheese)',
            'Olivet (cheese)',
            'Pithiviers (cheese)',
            'Feuille de Dreux (cheese)',
            'Gaperon (cheese)',
            'Bouton-de-Culotte (cheese)',
            'Baguette de Thierache (cheese)',
            'Brousse (cheese)',
            'Fribourg (cheese)',
            'Katschkawalj (cheese)',

            // 01.1.6 Fruit (HICP monitored)
            'Apples',
            'Pears',
            'Strawberries',
            'Oranges',
            'Bananas',
            'Lemon',
            'Grapes',
            'Plums',
            'Grapefruit',
            'Blueberries',
            'Raspberries',
            'Kiwi fruit',
            'Melon',
            'Pineapple',
            'Avocado',
            'Dried fruit',

            // 01.1.7 Vegetables (HICP monitored)
            'Potatoes',
            'Fresh tomatoes',
            'Cauliflower',
            'Mushrooms',
            'Lettuce',
            'Broccoli',
            'Sweet potatoes',
            'Canned pulses',
            'Canned tomatoes',
            'Pre-packed salad',
            'Peppers',
            'Cabbage',
            'Carrots',
            'Onions',
            'Cucumbers',
            'Courgettes',
            'Green beans',
            'Canned baked beans',
            'Canned sweetcorn',
            'Frozen peas',
            'Spinach',
            'Kale',
            'Brussels sprouts',

            // Legumes & Nuts
            'Lentils',
            'Chickpeas',
            'Black beans',
            'Kidney beans',
            'Almonds',
            'Walnuts',
            'Pumpkin seeds',
            'Sunflower seeds',

            // Seasonal Items - January
            'Citrus fruits (best in January)',
            'Winter squash (best in January)',
            'Leeks (best in January)',

            // Borough Market - Here & Now
            'Kale (best in January)',
            'Swede (best in January)',
            'Pomegranate (best in January)',
            'Lychees (best in January)',
            'January King cabbage (best in January)',
            'Conference pears (best in January)',
            'Figs (best in January)',
            'Sea kale (best in January)',
            'Shetland black potatoes (best in January)',
            'Dover sole (best in January)',
            'Bass (best in January)',
            'Herring (best in January)',
            'Sprats (best in January)',
            'Scallops (best in January)',
            'Venison (best in January)',
            'Pheasant (best in January)',
            'Woodcock (best in January)',
            'Partridge (best in January)',
            'Winter black truffle (best in January)',

            // Seasonal Items - February
            'Blood oranges (best in February)',
            'Parsnips (best in February)',
            'Purple sprouting broccoli (best in February)',

            // Borough Market - Here & Now
            'Forced rhubarb (best in February)',
            'Winter cauliflower (best in February)',
            'Seville oranges (best in February)',
            'Salt marsh lamb (best in February)',
            'Pork collar (best in February)',
            'Sea bass (best in February)',
            'Crab (best in February)',
            'Lobster (best in February)',
            'Clams (best in February)',
            'Mussels (best in February)',
            'Wild garlic (best in February)',
            'Black trompette mushrooms (best in February)',
            'Chanterelles (best in February)',
            'Kumquats (best in February)',
            'Israeli oranges (best in February)',
            'Israeli clementines (best in February)',

            // Seasonal Items - March
            'Rhubarb (best in March)',
            'Spring onions (best in March)',
            'Watercress (best in March)',

            // Borough Market - Here & Now
            'Wild garlic (best in March)',
            'Jersey royals (best in March)',
            'Spring greens (best in March)',
            'Ortanique (best in March)',
            'Cape plums (best in March)',
            'Heirloom tomatoes (best in March)',
            'Spanish aubergines (best in March)',
            'Dover sole (best in March)',
            'Turbot (best in March)',
            'Pollack (best in March)',
            'Gurnard (best in March)',
            'Plaice (best in March)',
            'Brill (best in March)',
            'Three cornered leek (best in March)',
            'Wild alexanders (best in March)',
            'Morel mushrooms (best in March)',
            'Black garlic (best in March)',
            'Mustard leaves (best in March)',
            'Red frills lettuce (best in March)',
            'Claytonia (best in March)',
            'Komatsuna (best in March)',
            'Grey mullet (best in March)',
            'Whiting (best in March)',

            // Seasonal Items - April
            'Asparagus (best in April)',
            'Artichokes (best in April)',
            'Spring lamb (best in April)',

            // Borough Market - Here & Now
            'Morel mushrooms (best in April)',
            'Rocket (best in April)',
            'Sorrel (best in April)',
            'Kentish wild garlic (best in April)',
            'Alexander (best in April)',
            'Lollo rosso lettuce (best in April)',
            'French breakfast radish (best in April)',
            'Punterella (best in April)',
            'Rapini (best in April)',
            'Frisée (best in April)',
            'Butterhead lettuce (best in April)',
            'Cavolo nero (best in April)',
            'Jerome cauliflower (best in April)',
            'Mayflower cauliflower (best in April)',
            'Hannibal leeks (best in April)',
            'Dogfish (best in April)',
            'Wild sea trout (best in April)',
            'British wild salmon (best in April)',
            'English rose veal (best in April)',
            'Curly kale (best in April)',
            'Outdoor rhubarb (best in April)',
            'Baby artichokes (best in April)',
            'Jerusalem artichokes (best in April)',

            // Seasonal Items - May
            'New potatoes (best in May)',
            'Radishes (best in May)',
            'Strawberries (best in May)',

            // Borough Market - Here & Now
            'Spring cabbage (best in May)',
            'Samphire (best in May)',
            'Fresh peas (best in May)',
            'St George mushrooms (best in May)',
            'Alexanders (best in May)',
            'Wild garlic (best in May)',
            'Claytonia (best in May)',
            'Bulls blood leaves (best in May)',
            'Jersey Royals (best in May)',
            'Broad beans (best in May)',
            'Lobsters (best in May)',
            'Langoustines (best in May)',
            'Black bream (best in May)',
            'Stawley goats cheese (best in May)',
            'Mousseron mushrooms (best in May)',
            'Three cornered leeks (best in May)',
            'Wild asparagus (best in May)',
            'Wild fennel (best in May)',
            'Artichokes (best in May)',
            'Chicory (best in May)',
            'Celeriac (best in May)',
            'Frissee (best in May)',
            'Radicchio (best in May)',
            'Wet garlic (best in May)',
            'Nasturtium root (best in May)',
            'Cuttlefish (best in May)',
            'John dory (best in May)',
            'Monkfish (best in May)',
            'Squid (best in May)',
            'American signal crayfish (best in May)',

            // Seasonal Items - June
            'Elderflowers (best in June)',
            'Broad beans (best in June)',
            'Gooseberries (best in June)',

            // Borough Market - Here & Now
            'Redcurrants (best in June)',
            'Lettuce (best in June)',
            'Early cherries (best in June)',
            'English cherries (best in June)',
            'Hass avocados (best in June)',
            'Apricots (best in June)',
            'Peaches (best in June)',
            'Nectarines (best in June)',
            'Fresh figs (best in June)',
            'Santa tomatoes (best in June)',
            'Greek melons (best in June)',
            'Wild asparagus (best in June)',
            'Nasturtiums (best in June)',
            'Cornflowers (best in June)',
            'Borage flowers (best in June)',
            'Nettles (best in June)',
            'Crystal cucumbers (best in June)',
            'Innes Log cheese (best in June)',
            'Haford cheddar (best in June)',
            'Wild sea bass (best in June)',
            'Wild salmon (best in June)',
            'Grey mullet (best in June)',
            'Black bream (best in June)',
            'Darjeeling first flush tea (best in June)',

            // Seasonal Items - July
            'Raspberries (best in July)',
            'Courgettes (best in July)',
            'Fennel (best in July)',

            // Borough Market - Here & Now
            'Blackcurrants (best in July)',
            'French beans (best in July)',
            'Summer herbs (best in July)',
            'Greengages (best in July)',
            'Red gooseberries (best in July)',
            'Douglas tomatoes (best in July)',
            'Cherry plum tomatoes (best in July)',
            'Yellow courgettes (best in July)',
            'Yellow French beans (best in July)',
            'Purple French beans (best in July)',
            'Courgette flowers (best in July)',
            'Broad bean flowers (best in July)',
            'Chocolate mint tip (best in July)',
            'Viola thyme flowers (best in July)',
            'Chive flowers (best in July)',
            'Elderflower (best in July)',
            'Meadowsweet (best in July)',
            'Trompette de la mort (best in July)',
            'Razor clams (best in July)',
            'Scottish squid (best in July)',
            'Cuttlefish (best in July)',
            'Doddington cheese (best in July)',
            'Scottish chanterelles (best in July)',
            'English ceps (best in July)',
            'Kohlrabi (best in July)',
            'Runner beans (best in July)',
            'English corn on the cob (best in July)',
            'Doughnut peaches (best in July)',
            'Turkish figs (best in July)',
            'William pears (best in July)',
            'Sakura tomatoes (best in July)',
            'San marzano tomatoes (best in July)',
            'Taster tomatoes (best in July)',
            'Marigold flowers (best in July)',
            'Green oakleaf lettuce (best in July)',
            'Red oakleaf lettuce (best in July)',
            'Lollo biondi (best in July)',
            'Alexander cheese (best in July)',
            'Howard cheese (best in July)',

            // Seasonal Items - August
            'Blackberries (best in August)',
            'Sweetcorn (best in August)',
            'Tomatoes (best in August)',

            // Borough Market - Here & Now
            'Peaches (best in August)',
            'Runner beans (best in August)',
            'Beetroot (best in August)',
            'Red grouse (best in August)',
            'Common snipe (best in August)',
            'Red stag (best in August)',
            'Fallow stag (best in August)',
            'Sika stag (best in August)',
            'Roe bucks (best in August)',
            'Cornish sardines (best in August)',
            'Dwarf beans (best in August)',
            'English kohlrabi (best in August)',
            'Red beetroot (best in August)',
            'White beetroot (best in August)',
            'Candy stripe beetroot (best in August)',
            'Black cabbage (best in August)',
            'Patty pan squashes (best in August)',
            'Purple spring onions (best in August)',
            'Oak leaf lettuce (best in August)',
            'Little gem lettuce (best in August)',
            'Lollo rosso (best in August)',
            'Cos lettuce (best in August)',
            'Red cos lettuce (best in August)',
            'Red batavia lettuce (best in August)',
            'Crystal lemons (best in August)',
            'Victoria plums (best in August)',
            'Red santa rosa plums (best in August)',
            'Ragstone cheese (best in August)',
            'Kentish cobnuts (best in August)',
            'Black figs (best in August)',
            'Italia grapes (best in August)',
            'Muscat grapes (best in August)',
            'Purple vitelotte potatoes (best in August)',
            'Cambodian palm sugar (best in August)',
            'Old Ford cheese (best in August)',
            'Stichelton cheese (best in August)',

            // Seasonal Items - September
            'Apples (best in September)',
            'Pears (best in September)',
            'Plums (best in September)',

            // Borough Market - Here & Now
            'Damsons (best in September)',
            'Cobnuts (best in September)',
            'Autumn squash (best in September)',
            'Russet apples (best in September)',
            'Cox apples (best in September)',
            'Bramley apples (best in September)',
            'Chegworth Beauty apples (best in September)',
            'Boskoop Rouge apples (best in September)',
            'Early Windsor apples (best in September)',
            'Spartan apples (best in September)',
            'Saturn apples (best in September)',
            'Blenheim Orange apples (best in September)',
            'Rabbits (best in September)',
            'Field mushrooms (best in September)',
            'Ceps (best in September)',
            'Pied de mouton (best in September)',
            'Hedgehog mushrooms (best in September)',
            'Rowan berries (best in September)',
            'Wild horseradish (best in September)',
            'Onion squashes (best in September)',
            'Giant puffball mushroom (best in September)',
            'Lemon sole (best in September)',
            'Gurnards (best in September)',
            'Walkers Spice Road cheese (best in September)',
            'Nicks Kitchen cheese (best in September)',
            'English truffles (best in September)',
            'Wet walnuts (best in September)',
            'Green walnuts (best in September)',
            'Cavolo nero cabbage (best in September)',
            'English green cabbage (best in September)',
            'Marrows (best in September)',
            'Wild plums (best in September)',
            'Patty pan squash (best in September)',
            'Crown prince squash (best in September)',
            'Egremont russet apples (best in September)',
            'Crimson crisp apples (best in September)',
            'Doyenne du comice pears (best in September)',
            'Conference pears (best in September)',
            'Williams pears (best in September)',
            'Forelle pears (best in September)',
            'Rododendro honey (best in September)',
            'Mallard (best in September)',

            // Seasonal Items - October
            'Pumpkins (best in October)',
            'Chestnuts (best in October)',
            'Wild mushrooms (best in October)',

            // Borough Market - Here & Now
            'Quinces (best in October)',
            'Walnuts (best in October)',
            'Medlars (best in October)',
            'Black cabbage (best in October)',
            'Crown prince squash (best in October)',
            'Festival squash (best in October)',
            'Onion squash (best in October)',
            'Marjories Seedling plums (best in October)',
            'Crimson crisp apples (best in October)',
            'Rainbow chard (best in October)',
            'Trooping funnels (best in October)',
            'Blewits (best in October)',
            'Charcoal burners (best in October)',
            'Wax caps (best in October)',
            'Parasol mushrooms (best in October)',
            'Rowan conserve (best in October)',
            'Oxtail (best in October)',
            'Ox cheek (best in October)',
            'Pig cheeks (best in October)',
            'Wild rabbit (best in October)',
            'Rosas Fire cheese (best in October)',
            'Sussex Mansion cheese (best in October)',
            'Romanesque cauliflower (best in October)',
            'Chicoria (best in October)',
            'Puntarella (best in October)',
            'Delicata squash (best in October)',
            'Turks turban (best in October)',
            'Ice plant (best in October)',
            'White borage flower (best in October)',
            'Brill (best in October)',
            'Turbot (best in October)',

            // Seasonal Items - November
            'Brussels sprouts (best in November)',
            'Cranberries (best in November)',
            'Celeriac (best in November)',

            // Borough Market - Here & Now
            'Pheasant (best in November)',
            'Venison (best in November)',
            'Sloes (best in November)',
            'Whiting (best in November)',
            'Wild bass (best in November)',
            'Sprats (best in November)',
            'Monkfish liver (best in November)',
            'Hare (best in November)',
            'Salt marsh lamb (best in November)',
            'Organic komatsuna (best in November)',
            'Sprout tops (best in November)',
            'Red curly kale (best in November)',
            'Rapini (best in November)',
            'Puntarella (best in November)',
            'Chervil root (best in November)',
            'Parsley root (best in November)',
            'French globe artichokes (best in November)',
            'Baby violet artichokes (best in November)',
            'Jerusalem artichokes (best in November)',
            'Persimmons (best in November)',
            'Brogdale apples (best in November)',
            'Ottobratica olive oil (best in November)',
            'Carolea olive oil (best in November)',
            'Chard (best in November)',
            'Savoy cabbage (best in November)',
            'Grey mullet (best in November)',
            'Halibut (best in November)',
            'Gomashio spice blend (best in November)',
            'Bermondsey Hard Pressed cheese (best in November)',
            'Red sprouts (best in November)',
            'Spaghetti squash (best in November)',
            'Swedes (best in November)',
            'Turnips (best in November)',
            'Hipsi cabbage (best in November)',
            'Frisee (best in November)',
            'Escarole (best in November)',
            'Braeburn apples (best in November)',
            'Jonagold apples (best in November)',
            'Gala apples (best in November)',
            'Goldfinger clementines (best in November)',
            'Custard apples (best in November)',
            'Orleans reinette apples (best in November)',
            'Allington pippin apples (best in November)',
            'Epine du mas apples (best in November)',
            'Prinses marijke apples (best in November)',
            'Laxtons superb apples (best in November)',
            'Old Fred apples (best in November)',
            'Riseley cheese (best in November)',
            'Baron bigod cheese (best in November)',

            // Seasonal Items - December
            'Winter cabbage (best in December)',
            'Clementines (best in December)',
            'Turnips (best in December)',

            // Borough Market - Here & Now
            'Forced chicory (best in December)',
            'Winter roots (best in December)',
            'Tangerines (best in December)',
            'Salsify (best in December)',
            'Romanesque broccoli (best in December)',
            'Kentish parsnips (best in December)',
            'Brussels sprout tops (best in December)',
            'Spanish oranges (best in December)',
            'Egyptian pomegranates (best in December)',
            'Cox apples (best in December)',
            'Russet apples (best in December)',
            'Gala apples (best in December)',
            'Braeburn apples (best in December)',
            'Bronze turkeys (best in December)',
            'Norfolk Black turkeys (best in December)',
            'Kelly Bronze turkeys (best in December)',
            'Norfolk Red turkeys (best in December)',
            'Geese (best in December)',
            'Cockerels (best in December)',
            'Ptarmigan (best in December)',
            'Wild duck (best in December)',
            'Teal (best in December)',
            'Traditional suet (best in December)',
            'Maris piper potatoes (best in December)',
            'Jerusalem artichokes (best in December)',
            'Black cabbage (best in December)',
            'Puntarella (best in December)',
            'Red topaz apples (best in December)',
            'Sharon fruit (best in December)',
            'Persimmon (best in December)',
            'Stichelton stilton (best in December)',
            'Colston Basset stilton (best in December)',
            'Arthurs Spice Road cheese (best in December)',
            'Mulled wine spices (best in December)',
            'Mint pepper jelly (best in December)',
            'Onion and chilli chutney (best in December)',
            'Prosciutto di Casentino (best in December)',
            'Rock Steady sauce (best in December)',
            'Banana and ginger chutney (best in December)',
            'Marron glacé (best in December)',
            'Escargot (best in December)',
            'Cumin cheese (best in December)',
            'Chilli cheese (best in December)',
            'Kirkhams Lancashire (best in December)',
            'Extra matured Lancashire (best in December)',

            // 01.2.1 Coffee, Tea and Cocoa (HICP monitored)
            'Tea bags',
            'Instant coffee',
            'Green tea',
            'Herbal tea',

            // 01.2.2 Mineral Waters, Soft Drinks and Juices (HICP monitored)
            'Pure fruit juices',
            'Fresh orange juice',
            'Fresh apple juice',
            'Mineral water',
            'Fruit / vegetable juice smoothie',
            'Alcohol-free beer',

            // 01.1.9 Other Food Products (HICP monitored)
            'Soup',
            'Mayonnaise',
            'Tomato ketchup',
            'Mustard',
            'Vinegar',
            'Salt',
            'Sugar',
            'Honey',
            'Jam',
            'Dried herbs',
            'Extra virgin olive oil',
            'Rapeseed oil',
            'Protein powder',

            // Additional Healthy Items
            'Coconut oil',
            'Avocado oil',
            'Fresh herbs (basil, parsley, cilantro)',
            'Turmeric',
            'Ginger',
            'Cinnamon',
            
            // Menu-specific ingredients
            'Oat flakes',
            'Rye flakes', 
            'Semolina',
            'Coconut flakes',
            'Almond flakes',
            'Croissants',
            'Celery',
            'Cocoa',
            'Capers',
            'Horseradish',
            'Olives',
            'Walnut oil',
            'Fish sauce',
            'Sweet chili sauce',
            'Sour cream',
            'Wine (cooking)',
            'Zucchini',
            'Buckwheat noodles',
            'Sesame seeds',
            'Soy sauce',
            'Pork ribs',
            'Sea bream',
            'Curry powder',
            'Mini eggplants',
            'Coconut cream',
            'Paprika',
            'Chili pepper',
            'Cornichons',
            'Veal',
            'Beef tongue',
            'Polenta',
            'Raisins',
            'Tarragon',
            'Masala spices',
            'Rum (cooking)',
            'Vanilla',
            'Durian',
            'Goat cheese',
            'Pistachios',
            'Waffles',
            'Papaya'
        ];
    }
}