/*
 * Copyright (c) 2013-2025 NoSocial.Net & Ivan Khvostishkov. Co-authored with Amazon Q
 */

class FoodDatabase {
    static getFoodList() {
        return [
            // 01.1.1 Bread and Cereals (HICP monitored)
            'Wholemeal bread',
            'White bread',
            'Bread rolls',
            'Flour',
            'Pasta',
            'Rice',
            'Breakfast cereals',
            'Hot oat cereal',
            'Biscuits (sweet snacks / cookies)',
            'Crackers (savory with cheese)',
            'Couscous',
            'Quinoa',
            'Pearl barley',
            'Buckwheat',

            // 01.1.2 Meat (HICP monitored)
            'Beef',
            'Lamb',
            'Pork',
            'Chicken',
            'Fresh diced turkey',
            'Pork sausages',
            'Ham',
            'Bacon',
            'Liver',

            // 01.1.3 Fish (HICP monitored)
            'Fresh white fish fillets',
            'Canned tuna',
            'Fresh salmon fillets',
            'Frozen prawns',
            'Sardines',
            'Mackerel',
            'Cod',
            'Herring',

            // 01.1.4 Milk, Cheese and Eggs (HICP monitored)
            'Semi-skimmed milk',
            'Full-fat milk',
            'Butter',
            'Eggs',
            'Yoghurt',
            'Cheddar',
            'Parmesan',
            'Soft cheese',
            'Greek yogurt',
            'Cottage cheese',
            'Mozzarella',
            'Feta cheese',
            
            // Common Cheeses
            'Brie (cheese)',
            'Camembert (cheese)',
            'Gouda (cheese)',
            'Edam (cheese)',
            'Emmental (cheese)',
            'Gruyere (cheese)',
            'Stilton (cheese)',
            'Roquefort (cheese)',
            'Gorgonzola (cheese)',
            'Cheshire (cheese)',
            'Lancashire (cheese)',
            'Neufchatel (cheese)',
            'Munster (cheese)',
            'Comte (cheese)',
            'Beaufort (cheese)',
            'Reblochon (cheese)',
            'Saint-Nectaire (cheese)',
            'Cantal (cheese)',
            'Maroilles (cheese)',
            'Livarot (cheese)',
            'Pont-l\'Eveque (cheese)',
            'Epoisses (cheese)',
            'Langres (cheese)',
            'Chaource (cheese)',
            'Saint-Marcellin (cheese)',
            'Crottin de Chavignol (cheese)',
            'Sainte-Maure (cheese)',
            'Pouligny-Saint-Pierre (cheese)',
            'Banon (cheese)',
            'Cabecou (cheese)',
            'Picodon (cheese)',
            'Pecorino (cheese)',
            'Provolone (cheese)',
            'Caciocavallo (cheese)',
            'Ricotta (cheese)',
            'Fontina (cheese)',
            'Asiago (cheese)',
            'Manchego (cheese)',
            'Mimolette (cheese)',
            'Port-Salut (cheese)',
            'Saint-Paulin (cheese)',
            'Fourme (cheese)',
            'Blue Cheshire (cheese)',
            'Coulommiers (cheese)',
            'Vacherin (cheese)',
            'Tomme (cheese)',
            'Appenzell (cheese)',
            'Sbrinz (cheese)',
            'Tilsitt (cheese)',
            'Limburger (cheese)',
            'Herve (cheese)',
            'Laguiole (cheese)',
            'Rollot (cheese)',
            'Saint-Florentin (cheese)',
            'Soumaintrain (cheese)',
            'Vendome (cheese)',
            'Brillat-Savarin (cheese)',
            'Excelsior (cheese)',
            'Fontainebleau (cheese)',
            'Petit-Suisse (cheese)',
            'Broccio (cheese)',
            'Venaco (cheese)',
            'Chevrotin (cheese)',
            'Rigotte (cheese)',
            'Selles-sur-Cher (cheese)',
            'Pelardon (cheese)',
            'Chabichou (cheese)',
            "Carre de l'Est (cheese)",
            'Gerome (cheese)',
            'Gris de Lille (cheese)',
            'Olivet (cheese)',
            'Pithiviers (cheese)',
            'Feuille de Dreux (cheese)',
            'Gaperon (cheese)',
            'Bouton-de-Culotte (cheese)',
            'Baguette de Thierache (cheese)',
            'Brousse (cheese)',
            'Fribourg (cheese)',
            'Kashkaval (cheese)',

            // 01.1.6 Fruit (HICP monitored)
            'Apples',
            'Pears',
            'Strawberries',
            'Oranges',
            'Bananas',
            'Lemon',
            'Grapes',
            'Plums',
            'Grapefruit',
            'Blueberries',
            'Raspberries',
            'Kiwi fruit',
            'Melon',
            'Pineapple',
            'Avocado',
            'Dried fruit',

            // 01.1.7 Vegetables (HICP monitored)
            'Potatoes',
            'Fresh tomatoes',
            'Cauliflower',
            'Mushrooms',
            'Lettuce',
            'Broccoli',
            'Sweet potatoes',
            'Canned pulses',
            'Canned tomatoes',
            'Pre-packed salad',
            'Peppers',
            'Cabbage',
            'Carrots',
            'Onions',
            'Cucumbers',
            'Courgettes',
            'Green beans',
            'Canned baked beans',
            'Canned sweetcorn',
            'Frozen peas',
            'Spinach',
            'Kale',
            'Brussels sprouts',

            // Legumes & Nuts
            'Lentils',
            'Chickpeas',
            'Black beans',
            'Kidney beans',
            'Almonds',
            'Walnuts',
            'Pumpkin seeds',
            'Sunflower seeds',

            // Seasonal Items - January
            'Citrus fruits (try in January)',
            'Winter squash (try in January)',
            'Leeks (try in January)',

            // Borough Market - Here & Now
            'Kale (try in January)',
            'Swede (try in January)',
            'Pomegranate (try in January)',
            'Lychees (try in January)',
            'January King cabbage (try in January)',
            'Conference pears (try in January)',
            'Figs (try in January)',
            'Sea kale (try in January)',
            'Shetland black potatoes (try in January)',
            'Dover sole (try in January)',
            'Bass (try in January)',
            'Herring (try in January)',
            'Sprats (try in January)',
            'Scallops (try in January)',
            'Venison (try in January)',
            'Pheasant (try in January)',
            'Woodcock (try in January)',
            'Partridge (try in January)',
            'Winter black truffle (try in January)',

            // Seasonal Items - February
            'Blood oranges (try in February)',
            'Parsnips (try in February)',
            'Purple sprouting broccoli (try in February)',

            // Borough Market - Here & Now
            'Forced rhubarb (try in February)',
            'Winter cauliflower (try in February)',
            'Seville oranges (try in February)',
            'Salt marsh lamb (try in February)',
            'Pork collar (try in February)',
            'Sea bass (try in February)',
            'Crab (try in February)',
            'Lobster (try in February)',
            'Clams (try in February)',
            'Mussels (try in February)',
            'Wild garlic (try in February)',
            'Black trompette mushrooms (try in February)',
            'Chanterelles (try in February)',
            'Kumquats (try in February)',
            'Israeli oranges (try in February)',
            'Israeli clementines (try in February)',

            // Seasonal Items - March
            'Rhubarb (try in March)',
            'Spring onions (try in March)',
            'Watercress (try in March)',

            // Borough Market - Here & Now
            'Wild garlic (try in March)',
            'Jersey royals (try in March)',
            'Spring greens (try in March)',
            'Ortanique (try in March)',
            'Cape plums (try in March)',
            'Heirloom tomatoes (try in March)',
            'Spanish aubergines (try in March)',
            'Dover sole (try in March)',
            'Turbot (try in March)',
            'Pollack (try in March)',
            'Gurnard (try in March)',
            'Plaice (try in March)',
            'Brill (try in March)',
            'Three cornered leek (try in March)',
            'Wild alexanders (try in March)',
            'Morel mushrooms (try in March)',
            'Black garlic (try in March)',
            'Mustard leaves (try in March)',
            'Red frills lettuce (try in March)',
            'Claytonia (try in March)',
            'Komatsuna (try in March)',
            'Grey mullet (try in March)',
            'Whiting (try in March)',

            // Seasonal Items - April
            'Asparagus (try in April)',
            'Artichokes (try in April)',
            'Spring lamb (try in April)',

            // Borough Market - Here & Now
            'Morel mushrooms (try in April)',
            'Rocket (try in April)',
            'Sorrel (try in April)',
            'Kentish wild garlic (try in April)',
            'Alexander (try in April)',
            'Lollo rosso lettuce (try in April)',
            'French breakfast radish (try in April)',
            'Punterella (try in April)',
            'Rapini (try in April)',
            'Frisée (try in April)',
            'Butterhead lettuce (try in April)',
            'Cavolo nero (try in April)',
            'Jerome cauliflower (try in April)',
            'Mayflower cauliflower (try in April)',
            'Hannibal leeks (try in April)',
            'Dogfish (try in April)',
            'Wild sea trout (try in April)',
            'British wild salmon (try in April)',
            'English rose veal (try in April)',
            'Curly kale (try in April)',
            'Outdoor rhubarb (try in April)',
            'Baby artichokes (try in April)',
            'Jerusalem artichokes (try in April)',

            // Seasonal Items - May
            'New potatoes (try in May)',
            'Radishes (try in May)',
            'Strawberries (try in May)',

            // Borough Market - Here & Now
            'Spring cabbage (try in May)',
            'Samphire (try in May)',
            'Fresh peas (try in May)',
            'St George mushrooms (try in May)',
            'Alexanders (try in May)',
            'Wild garlic (try in May)',
            'Claytonia (try in May)',
            'Bulls blood leaves (try in May)',
            'Jersey Royals (try in May)',
            'Broad beans (try in May)',
            'Lobsters (try in May)',
            'Langoustines (try in May)',
            'Black bream (try in May)',
            'Stawley goats cheese (try in May)',
            'Mousseron mushrooms (try in May)',
            'Three cornered leeks (try in May)',
            'Wild asparagus (try in May)',
            'Wild fennel (try in May)',
            'Artichokes (try in May)',
            'Chicory (try in May)',
            'Celeriac (try in May)',
            'Frissee (try in May)',
            'Radicchio (try in May)',
            'Wet garlic (try in May)',
            'Nasturtium root (try in May)',
            'Cuttlefish (try in May)',
            'John dory (try in May)',
            'Monkfish (try in May)',
            'Squid (try in May)',
            'American signal crayfish (try in May)',

            // Seasonal Items - June
            'Elderflowers (try in June)',
            'Broad beans (try in June)',
            'Gooseberries (try in June)',

            // Borough Market - Here & Now
            'Redcurrants (try in June)',
            'Lettuce (try in June)',
            'Early cherries (try in June)',
            'English cherries (try in June)',
            'Hass avocados (try in June)',
            'Apricots (try in June)',
            'Peaches (try in June)',
            'Nectarines (try in June)',
            'Fresh figs (try in June)',
            'Santa tomatoes (try in June)',
            'Greek melons (try in June)',
            'Wild asparagus (try in June)',
            'Nasturtiums (try in June)',
            'Cornflowers (try in June)',
            'Borage flowers (try in June)',
            'Nettles (try in June)',
            'Crystal cucumbers (try in June)',
            'Innes Log cheese (try in June)',
            'Haford cheddar (try in June)',
            'Wild sea bass (try in June)',
            'Wild salmon (try in June)',
            'Grey mullet (try in June)',
            'Black bream (try in June)',
            'Darjeeling first flush tea (try in June)',

            // Seasonal Items - July
            'Raspberries (try in July)',
            'Courgettes (try in July)',
            'Fennel (try in July)',

            // Borough Market - Here & Now
            'Blackcurrants (try in July)',
            'French beans (try in July)',
            'Summer herbs (try in July)',
            'Greengages (try in July)',
            'Red gooseberries (try in July)',
            'Douglas tomatoes (try in July)',
            'Cherry plum tomatoes (try in July)',
            'Yellow courgettes (try in July)',
            'Yellow French beans (try in July)',
            'Purple French beans (try in July)',
            'Courgette flowers (try in July)',
            'Broad bean flowers (try in July)',
            'Chocolate mint tip (try in July)',
            'Viola thyme flowers (try in July)',
            'Chive flowers (try in July)',
            'Elderflower (try in July)',
            'Meadowsweet (try in July)',
            'Trompette de la mort (try in July)',
            'Razor clams (try in July)',
            'Scottish squid (try in July)',
            'Cuttlefish (try in July)',
            'Doddington cheese (try in July)',
            'Scottish chanterelles (try in July)',
            'English ceps (try in July)',
            'Kohlrabi (try in July)',
            'Runner beans (try in July)',
            'English corn on the cob (try in July)',
            'Doughnut peaches (try in July)',
            'Turkish figs (try in July)',
            'William pears (try in July)',
            'Sakura tomatoes (try in July)',
            'San marzano tomatoes (try in July)',
            'Taster tomatoes (try in July)',
            'Marigold flowers (try in July)',
            'Green oakleaf lettuce (try in July)',
            'Red oakleaf lettuce (try in July)',
            'Lollo biondi (try in July)',
            'Alexander cheese (try in July)',
            'Howard cheese (try in July)',

            // Seasonal Items - August
            'Blackberries (try in August)',
            'Sweetcorn (try in August)',
            'Tomatoes (try in August)',

            // Borough Market - Here & Now
            'Peaches (try in August)',
            'Runner beans (try in August)',
            'Beetroot (try in August)',
            'Red grouse (try in August)',
            'Common snipe (try in August)',
            'Red stag (try in August)',
            'Fallow stag (try in August)',
            'Sika stag (try in August)',
            'Roe bucks (try in August)',
            'Cornish sardines (try in August)',
            'Dwarf beans (try in August)',
            'English kohlrabi (try in August)',
            'Red beetroot (try in August)',
            'White beetroot (try in August)',
            'Candy stripe beetroot (try in August)',
            'Black cabbage (try in August)',
            'Patty pan squashes (try in August)',
            'Purple spring onions (try in August)',
            'Oak leaf lettuce (try in August)',
            'Little gem lettuce (try in August)',
            'Lollo rosso (try in August)',
            'Cos lettuce (try in August)',
            'Red cos lettuce (try in August)',
            'Red batavia lettuce (try in August)',
            'Crystal lemons (try in August)',
            'Victoria plums (try in August)',
            'Red santa rosa plums (try in August)',
            'Ragstone cheese (try in August)',
            'Kentish cobnuts (try in August)',
            'Black figs (try in August)',
            'Italia grapes (try in August)',
            'Muscat grapes (try in August)',
            'Purple vitelotte potatoes (try in August)',
            'Cambodian palm sugar (try in August)',
            'Old Ford cheese (try in August)',
            'Stichelton cheese (try in August)',

            // Seasonal Items - September
            'Apples (try in September)',
            'Pears (try in September)',
            'Plums (try in September)',

            // Borough Market - Here & Now
            'Damsons (try in September)',
            'Cobnuts (try in September)',
            'Autumn squash (try in September)',
            'Russet apples (try in September)',
            'Cox apples (try in September)',
            'Bramley apples (try in September)',
            'Chegworth Beauty apples (try in September)',
            'Boskoop Rouge apples (try in September)',
            'Early Windsor apples (try in September)',
            'Spartan apples (try in September)',
            'Saturn apples (try in September)',
            'Blenheim Orange apples (try in September)',
            'Rabbits (try in September)',
            'Field mushrooms (try in September)',
            'Ceps (try in September)',
            'Pied de mouton (try in September)',
            'Hedgehog mushrooms (try in September)',
            'Rowan berries (try in September)',
            'Wild horseradish (try in September)',
            'Onion squashes (try in September)',
            'Giant puffball mushroom (try in September)',
            'Lemon sole (try in September)',
            'Gurnards (try in September)',
            'Walkers Spice Road cheese (try in September)',
            'Nicks Kitchen cheese (try in September)',
            'English truffles (try in September)',
            'Wet walnuts (try in September)',
            'Green walnuts (try in September)',
            'Cavolo nero cabbage (try in September)',
            'English green cabbage (try in September)',
            'Marrows (try in September)',
            'Wild plums (try in September)',
            'Patty pan squash (try in September)',
            'Crown prince squash (try in September)',
            'Egremont russet apples (try in September)',
            'Crimson crisp apples (try in September)',
            'Doyenne du comice pears (try in September)',
            'Conference pears (try in September)',
            'Williams pears (try in September)',
            'Forelle pears (try in September)',
            'Rododendro honey (try in September)',
            'Mallard (try in September)',

            // Seasonal Items - October
            'Pumpkins (try in October)',
            'Chestnuts (try in October)',
            'Wild mushrooms (try in October)',

            // Borough Market - Here & Now
            'Quinces (try in October)',
            'Walnuts (try in October)',
            'Medlars (try in October)',
            'Black cabbage (try in October)',
            'Crown prince squash (try in October)',
            'Festival squash (try in October)',
            'Onion squash (try in October)',
            'Marjories Seedling plums (try in October)',
            'Crimson crisp apples (try in October)',
            'Rainbow chard (try in October)',
            'Trooping funnels (try in October)',
            'Blewits (try in October)',
            'Charcoal burners (try in October)',
            'Wax caps (try in October)',
            'Parasol mushrooms (try in October)',
            'Rowan conserve (try in October)',
            'Oxtail (try in October)',
            'Ox cheek (try in October)',
            'Pig cheeks (try in October)',
            'Wild rabbit (try in October)',
            'Rosas Fire cheese (try in October)',
            'Sussex Mansion cheese (try in October)',
            'Romanesque cauliflower (try in October)',
            'Chicoria (try in October)',
            'Puntarella (try in October)',
            'Delicata squash (try in October)',
            'Turks turban (try in October)',
            'Ice plant (try in October)',
            'White borage flower (try in October)',
            'Brill (try in October)',
            'Turbot (try in October)',

            // Seasonal Items - November
            'Brussels sprouts (try in November)',
            'Cranberries (try in November)',
            'Celeriac (try in November)',

            // Borough Market - Here & Now
            'Pheasant (try in November)',
            'Venison (try in November)',
            'Sloes (try in November)',
            'Whiting (try in November)',
            'Wild bass (try in November)',
            'Sprats (try in November)',
            'Monkfish liver (try in November)',
            'Hare (try in November)',
            'Salt marsh lamb (try in November)',
            'Organic komatsuna (try in November)',
            'Sprout tops (try in November)',
            'Red curly kale (try in November)',
            'Rapini (try in November)',
            'Puntarella (try in November)',
            'Chervil root (try in November)',
            'Parsley root (try in November)',
            'French globe artichokes (try in November)',
            'Baby violet artichokes (try in November)',
            'Jerusalem artichokes (try in November)',
            'Persimmons (try in November)',
            'Brogdale apples (try in November)',
            'Ottobratica olive oil (try in November)',
            'Carolea olive oil (try in November)',
            'Chard (try in November)',
            'Savoy cabbage (try in November)',
            'Grey mullet (try in November)',
            'Halibut (try in November)',
            'Gomashio spice blend (try in November)',
            'Bermondsey Hard Pressed cheese (try in November)',
            'Red sprouts (try in November)',
            'Spaghetti squash (try in November)',
            'Swedes (try in November)',
            'Turnips (try in November)',
            'Hipsi cabbage (try in November)',
            'Frisee (try in November)',
            'Escarole (try in November)',
            'Braeburn apples (try in November)',
            'Jonagold apples (try in November)',
            'Gala apples (try in November)',
            'Goldfinger clementines (try in November)',
            'Custard apples (try in November)',
            'Orleans reinette apples (try in November)',
            'Allington pippin apples (try in November)',
            'Epine du mas apples (try in November)',
            'Prinses marijke apples (try in November)',
            'Laxtons superb apples (try in November)',
            'Old Fred apples (try in November)',
            'Riseley cheese (try in November)',
            'Baron bigod cheese (try in November)',

            // Seasonal Items - December
            'Winter cabbage (try in December)',
            'Clementines (try in December)',
            'Turnips (try in December)',

            // Borough Market - Here & Now
            'Forced chicory (try in December)',
            'Winter roots (try in December)',
            'Tangerines (try in December)',
            'Salsify (try in December)',
            'Romanesque broccoli (try in December)',
            'Kentish parsnips (try in December)',
            'Brussels sprout tops (try in December)',
            'Spanish oranges (try in December)',
            'Egyptian pomegranates (try in December)',
            'Cox apples (try in December)',
            'Russet apples (try in December)',
            'Gala apples (try in December)',
            'Braeburn apples (try in December)',
            'Bronze turkeys (try in December)',
            'Norfolk Black turkeys (try in December)',
            'Kelly Bronze turkeys (try in December)',
            'Norfolk Red turkeys (try in December)',
            'Geese (try in December)',
            'Cockerels (try in December)',
            'Ptarmigan (try in December)',
            'Wild duck (try in December)',
            'Teal (try in December)',
            'Traditional suet (try in December)',
            'Maris piper potatoes (try in December)',
            'Jerusalem artichokes (try in December)',
            'Black cabbage (try in December)',
            'Puntarella (try in December)',
            'Red topaz apples (try in December)',
            'Sharon fruit (try in December)',
            'Persimmon (try in December)',
            'Stichelton stilton (try in December)',
            'Colston Basset stilton (try in December)',
            'Arthurs Spice Road cheese (try in December)',
            'Mulled wine spices (try in December)',
            'Mint pepper jelly (try in December)',
            'Onion and chilli chutney (try in December)',
            'Prosciutto di Casentino (try in December)',
            'Rock Steady sauce (try in December)',
            'Banana and ginger chutney (try in December)',
            'Marron glacé (try in December)',
            'Escargot (try in December)',
            'Cumin cheese (try in December)',
            'Chilli cheese (try in December)',
            'Kirkhams Lancashire (try in December)',
            'Extra matured Lancashire (try in December)',

            // 01.2.1 Coffee, Tea and Cocoa (HICP monitored)
            'Tea bags',
            'Instant coffee',
            'Green tea',
            'Herbal tea',

            // 01.2.2 Mineral Waters, Soft Drinks and Juices (HICP monitored)
            'Pure fruit juices',
            'Fresh orange juice',
            'Fresh apple juice',
            'Mineral water',
            'Fruit / vegetable juice smoothie',
            'Alcohol-free beer',

            // 01.1.9 Other Food Products (HICP monitored)
            'Soup',
            'Mayonnaise',
            'Tomato ketchup',
            'Mustard',
            'Vinegar',
            'Salt',
            'Sugar',
            'Honey',
            'Jam',
            'Dried herbs',
            'Extra virgin olive oil',
            'Rapeseed oil',
            'Protein powder',

            // Additional Healthy Items
            'Coconut oil',
            'Avocado oil',
            'Fresh herbs (basil, parsley, cilantro)',
            'Turmeric',
            'Ginger',
            'Cinnamon',
            
            // Menu-specific ingredients
            'Oat flakes',
            'Rye flakes', 
            'Semolina',
            'Coconut flakes',
            'Almond flakes',
            'Croissants',
            'Celery',
            'Cocoa',
            'Capers',
            'Horseradish',
            'Olives',
            'Walnut oil',
            'Fish sauce',
            'Sweet chili sauce',
            'Sour cream',
            'Wine (cooking)',
            'Zucchini',
            'Buckwheat noodles',
            'Sesame seeds',
            'Soy sauce',
            'Pork ribs',
            'Sea bream',
            'Curry powder',
            'Mini eggplants',
            'Coconut cream',
            'Paprika',
            'Chili pepper',
            'Cornichons',
            'Veal',
            'Beef tongue',
            'Polenta',
            'Raisins',
            'Tarragon',
            'Masala spices',
            'Rum (cooking)',
            'Vanilla',
            'Durian',
            'Goat cheese',
            'Pistachios',
            'Waffles',
            'Papaya'
        ];
    }
}